name: Update Hashes

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    update-hashes:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Zip resourcepacks
              run: |
                chmod +x unzip/buildpacks.sh
                ./unzip/buildpacks.sh

            - name: Setup Script
              run: |
                cd packs
                chmod +x generateHash.sh
                ./generateHash.sh

            - name: Commit changes
              id: commit
              run: |
                git config --global user.name "Github Action"
                git config --global user.email "action@github.com"
                TIMESTAMP=$(date +%s)
                BRANCH_NAME="update-hashes-$TIMESTAMP"
                git checkout -b "$BRANCH_NAME"
                git add packs/*.sha1
                if git commit -m "Update SHA1 for Packs"; then
                    git push origin "$BRANCH_NAME"
                    echo "branch=$BRANCH_NAME" | tee -a "$GITHUB_OUTPUT"
                    echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"
                    echo "Branch created and pushed: $BRANCH_NAME"
                else
                    echo "No changes"
                    echo "branch=" | tee -a "$GITHUB_OUTPUT"
                fi
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Debug output
              run: |
                echo "Branch from commit step: ${{ steps.commit.outcome.branch }}"

            - name: Create PR
              if: success() && env.BRANCH_NAME != ''
              uses: peter-evans/create-pull-request@v5
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ env.BRANCH_NAME }}
                base: main
                title: "Update SHA1 Hashes"
                body: "Automated pull request"
                commit-message: "Update SHA1 files for ZIP Packs"
